### PR TITLE
Automatically add IDL library directory

### PR DESCRIPTION
**Pull request by lstagner**

### CODE REVIEW

**Comment by BobPortmann** [comment]
This is nice. Thanks for it. Unfortunately it does not work on Mac OS X for the Callable case. I get the following error

```
JL_IDL_TYPE=CALLABLE ~/Applications/Julia-0.5.app/Contents/Resources/julia/bin/julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> import IDLCall
ERROR: LoadError: error compiling init: could not load library "libidl"
dlopen(/Applications/exelis/idl/bin/bin.darwin.x86_64/libidl.dylib, 1): Library not loaded: libMesaGLU6_2.dylib
  Referenced from: /Applications/exelis/idl/bin/bin.darwin.x86_64/libidl.dylib
  Reason: image not found
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Users/portmann/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /Users/portmann/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in require(::Symbol) at ./loading.jl:415
 in require(::Symbol) at /Users/portmann/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/portmann/lib/julia/IDLCall.jl/src/IDLCall.jl, in expression starting on line 24

julia> Libdl.DL_LOAD_PATH
3-element Array{String,1}:
 "@loader_path/julia"                            
 "@loader_path"                                  
 "/Applications/exelis/idl/bin/bin.darwin.x86_64"
```

I'm not sure why this happens but it loads ok if I use the DYLD_FALLBACK_LIBRARY_PATH method I mention in the README. Thus I think you will have to make this `is_linux()` only. Maybe I can set the DYLD_FALLBACK_LIBRARY_PATH variable in julia to make it start automatically on Mac OS X. I'll look into that.

**Comment by lstagner** [comment]
I made the suggested change. It may be a good idea to ping someone who is more familiar with dealing with macOS's eccentricities.

**Comment by lstagner** [comment]
I think this

```
ENV["DYLD_FALLBACK_LIBRARY_PATH"] = "/Applications/exelis/idl/bin/bin.darwin.x86_64/"
```

might work for the macOS case.

**Comment by BobPortmann** [comment]
It doesn't work, either at the command line or in my `.juliarc.jl`. It seems `julia` must inherit it from the shell.

**Pull request merged**
