### PR TITLE
Automatically startup IDLRPC

### PR DESCRIPTION
**Pull request by lstagner**

### CODE REVIEW

**Comment by BobPortmann** [comment]
Thanks for looking at this and I could see many people liking this approach. I, on the other hand, like to start my `idlrpc` in a shell (usually using `screen` which I detach) and then I can kill and  restart the julia session several times w/o restarting the IDL session (this is one reason I like idlrpc better than idlcallable). Thus, I do not like your change that always kills the `idlrpc` session at exit. If you did not register the `cleanup` routine using `atexit` if `init` finds that `idlrpc` is already running then I would be OK with these changes. What do you think?

**Comment by BobPortmann** [comment]
Also, it's a small thing but I generally try to follow the style of the julia lang coding style including putting spaces after most commas (and yes I see that I have not followed this perfectly, which I will try to fix at some point). Thus, can you add spaces after commas in function calls, Union statements, constructor calls, etc. Thanks.

**Comment by lstagner** [comment]
Hmm. I suppose you were killing the Julia process in a way that didn't use your old `exit()` function? Anyway I can see the advantage of having the option to keep the `idlrpc` session alive between Julia sessions. This should be good to go now.

**Comment by BobPortmann** [comment]
Yes, I never used `exit` and just killed the `idlrpc` in the shell. But it is probably not ideal that I never called `IDL_RPCCleanup` .

After looking at this some more I think that it would be best to always register the `atexit` callback (probably at the bottom of `init`) but call `IDL_RPCCleanup` with `ikill` (the last input) equal to `0`. This allows still allows  `idlrpc` to continue in the case it is started externally and makes `kill(pclient.process)` kills the process in the case `idlrpc` is started by `IDLCall`.

You can make this change or I can push it after merging this? Let me know.

**Comment by lstagner** [comment]
OK I made the suggested changes.

**Comment by BobPortmann** [comment]
OK. Thanks for this. It is a nice improvement.

**Pull request merged**
