### PR TITLE
Use full library path for linux and macOS

### PR DESCRIPTION
**Pull request by lstagner**
This should fix the macOS load path issue.

### CODE REVIEW

**Comment by BobPortmann** [comment]
Your fix works perfectly using rpc. Nice.

Using callable it does not work on either julia 0.4.7 or 0.5. The error on 0.5 is:

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> ENV["JL_IDL_TYPE"] = "CALLABLE";

julia> import IDLCall
ERROR: LoadError: error compiling init: could not load library "/Applications/exelis/idl/bin/bin.darwin.x86_64/libidl"
dlopen(/Applications/exelis/idl/bin/bin.darwin.x86_64/libidl.dylib, 1): Library not loaded: libMesaGLU6_2.dylib
  Referenced from: /Applications/exelis/idl/bin/bin.darwin.x86_64/libidl.dylib
  Reason: image not found
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Users/name/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /Users/name/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in require(::Symbol) at ./loading.jl:415
 in require(::Symbol) at /Users/name/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/name/lib/julia/IDLCall.jl/src/IDLCall.jl, in expression starting on line 28
```

If I change the `init()` call in IDLCall.jl to `cd(init, idl_lib_dir)` then callable works using julia 0.4.7 but not when using 0.5. The error is:

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> ENV["JL_IDL_TYPE"] = "CALLABLE";

julia> import IDLCall
ERROR: LoadError: error compiling cd: error compiling init: could not load library "/Applications/exelis/idl/bin/bin.darwin.x86_64/libidl"
dlopen(/Applications/exelis/idl/bin/bin.darwin.x86_64/libidl.dylib, 1): Library not loaded: libMesaGLU6_2.dylib
  Referenced from: /Applications/exelis/idl/bin/bin.darwin.x86_64/libidl.dylib
  Reason: image not found
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Users/name/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /Users/name/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in require(::Symbol) at ./loading.jl:415
 in require(::Symbol) at /Users/name/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/name/lib/julia/IDLCall.jl/src/IDLCall.jl, in expression starting on line 29
```

**Comment by lstagner** [comment]
That is the same error as last time. This is getting annoying. I found [this stackoverflow question](http://stackoverflow.com/questions/38468764/idl-python-bridge-fails-due-to-sip-on-osx-el-capitan) that may be the reason why its not working.

**Comment by BobPortmann** [comment]
Interesting but I'm on OS X Yosemite 10.10.5, which doesn't include SIP (AFAICT). Also, in case it matters, I'm using IDL 8.5. I guess I should try 8.5.1. I'll look into that but it could take a few weeks.

**Comment by BobPortmann** [comment]
Plus they are using `DYLD_LIBRARY_PATH` and still can't get it to work because of SIP. This means that on El Capitan or above the workaround using `DYLD_FALLBACK_LIBRARY_PATH` may no longer work.

My impression is that if `DYLD_LIBRARY_PATH` (or the fallback version) is needed that means the library was not correctly made.

**Comment by lstagner** [comment]
Well since this doesn't work this PR doesn't really add anything. 

I talked with some of the people in the Julia gitter room and they pointed me to this [issue](http://stackoverflow.com/questions/6713692/problems-with-using-setenv-and-then-making-the-dlopen-call) . Long story short it looks like we are stuck with manually setting `DYLIB_FALLBACK_LIBRARY_PATH` for macOS.

**Comment by lstagner** [comment]
There is a workaround but it requires you to restart the julia process after you use ENV to set the environmental variable; loosing all your variables in the process. 

If you want to try it all you need to do is this

``` julia
ENV["DYLD_FALLBACK_LIBRARY_PATH"] ="/Applications/exelis/idl/bin/bin.darwin.x86_64"
ccall(:execve, Cint, (Cstring, Ptr{Cstring}, Ptr{Cstring}),
             "/home/lstagner/julia/bin/julia", ["julia","-q"],
             unsafe_load(Ptr{Ptr{Cstring}}(cglobal(:environ))))
```

replacing my julia path with yours

**Comment by lstagner** [comment]
Actually this might work while preserving the set variables

```
ENV["DYLD_FALLBACK_LIBRARY_PATH"] ="/Applications/exelis/idl/bin/bin.darwin.x86_64"
workspace()
for name in setdiff(names(Main.LastMain, true), names(Main, true))
    @eval import Main.LastMain.$name
end
```

but it may not be an extreme enough reset.

**Comment by BobPortmann** [comment]
Your fix works for `IDLRPC` which is a step forward. We only have to make people set `DYLD_FALLBACK_LIBRARY_PATH` for `IDLCALLABLE`.

Note that the `cd` trick worked on 0.4.7 but not on 0.5.0. I'm trying to find the issue that changed that but cannot.

Here is a simple way to diagnose the problem. Both of these approaches work on 0.5.0 (starting from a fresh start:

```
julia> push!(Libdl.DL_LOAD_PATH, "/Applications/exelis/idl/bin/bin.darwin.x86_64")
3-element Array{String,1}:
 "@loader_path/julia"                            
 "@loader_path"                                  
 "/Applications/exelis/idl/bin/bin.darwin.x86_64"

julia> Libdl.dlopen("libidl_rpc")
Ptr{Void} @0x00007fa75246aa30
```

or

```
julia> Libdl.dlopen("/Applications/exelis/idl/bin/bin.darwin.x86_64/libidl_rpc")
Ptr{Void} @0x00007fb5b3219c90
```

Trying to open "libidl" these both fail with the error above. But on 0.4.7 this works:

```
julia> cd("/Applications/exelis/idl/bin/bin.darwin.x86_64") do 
           Libdl.dlopen("libidl")
       end
Ptr{Void} @0x00007f803c04f550
```

which I find interesting. Wish I could find the issue that changed this behavior.

**Comment by BobPortmann** [comment]
In case it helps someone, here is the output of otool:

```
~> otool -L /Applications/exelis/idl85/bin/bin.darwin.x86_64/libidl_rpc.dylib 
/Applications/exelis/idl85/bin/bin.darwin.x86_64/libidl_rpc.dylib:
        libidl_rpc.8.5.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)
```

```
~> otool -L /Applications/exelis/idl85/bin/bin.darwin.x86_64/libidl.dylib 
/Applications/exelis/idl85/bin/bin.darwin.x86_64/libidl.dylib:
        libidl.8.5.dylib (compatibility version 0.0.0, current version 0.0.0)
        /opt/X11/lib/libfreetype.6.dylib (compatibility version 15.0.0, current version 15.1.0)
        /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 57.0.0)
        /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
        /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 19.0.0)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 744.0.0)
        libMesaGLU6_2.dylib (compatibility version 0.0.0, current version 0.0.0)
        libMesaGL6_2.dylib (compatibility version 0.0.0, current version 0.0.0)
        libOSMesa6_2.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)
        /opt/X11/lib/libXp.6.dylib (compatibility version 9.0.0, current version 9.0.0)
        libXm.3.0.2.dylib (compatibility version 4.0.0, current version 4.2.0)
        /opt/X11/lib/libXpm.4.dylib (compatibility version 16.0.0, current version 16.0.0)
        /opt/X11/lib/libXmu.6.dylib (compatibility version 9.0.0, current version 9.0.0)
        /opt/X11/lib/libXext.6.dylib (compatibility version 11.0.0, current version 11.0.0)
        /opt/X11/lib/libXt.6.dylib (compatibility version 7.0.0, current version 7.0.0)
        /opt/X11/lib/libXinerama.1.dylib (compatibility version 2.0.0, current version 2.0.0)
        /opt/X11/lib/libSM.6.dylib (compatibility version 7.0.0, current version 7.1.0)
        /opt/X11/lib/libICE.6.dylib (compatibility version 10.0.0, current version 10.0.0)
        /opt/X11/lib/libX11.6.dylib (compatibility version 10.0.0, current version 10.0.0)
        /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1187.0.0)
        /usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

And your workarounds above do exactly what you suspected: the 1st works but you lose all variables. The 2nd (workspace method) does not work.

**Comment by lstagner** [comment]
You might want to try playing with [dlopens flags](http://docs.julialang.org/en/release-0.5/stdlib/libdl/#Base.Libdl.dlopen) specifically changing `RTLD_GLOBAL` to `RTLD_LOCAL` which is what the linker uses on linux e.g.

``` julia
using Base.Libdl
dlopen("/Applications/exelis/idl/bin/bin.darwin.x86_64/libidl", RTLD_LAZY | RTLD_DEEPBIND | RTLD_LOCAL)
```

no idea if it will work but its worth a shot.

**Comment by BobPortmann** [comment]
I've tried many combinations of those flags and nothing works. Here is an issue that addresses the problem we are having https://github.com/JuliaLang/julia/issues/7004. I suppose on linux the paths inside `libidl.so` file are absolute? Maybe you could check with the `ldd` command (see the linked issue).

Since the linker will find the first library but not the ones insides it (unless they are on the normal path, or absolute paths), it seems I should be able to do a trick: set `DL_LOAD_PATH`, directly open the librarys need explicity and then the linker will find them. Unfortunately I do not know how to do this. What do I do with the pointer returned from `dlopen`? Am I suppose to use `dlsym`?

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> push!(Libdl.DL_LOAD_PATH, "/Applications/exelis/idl/bin/bin.darwin.x86_64")
3-element Array{String,1}:
 "@loader_path/julia"                            
 "@loader_path"                                  
 "/Applications/exelis/idl/bin/bin.darwin.x86_64"

julia> Libdl.dlopen("libMesaGL6_2.dylib")
Ptr{Void} @0x00007fbbfa71c740

julia> Libdl.dlopen("libMesaGLU6_2.dylib")
ERROR: could not load library "libMesaGLU6_2.dylib"
dlopen(/Applications/exelis/idl/bin/bin.darwin.x86_64/libMesaGLU6_2.dylib, 1): Library not loaded: libMesaGL6_2.dylib
  Referenced from: /Applications/exelis/idl/bin/bin.darwin.x86_64/libMesaGLU6_2.dylib
  Reason: image not found
 in dlopen(::String, ::UInt32) at ./libdl.jl:90 (repeats 2 times)
 in dlopen(::String) at /Users/portmann/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
```

Notice that it can dlopen libMesaGL6_2.dylib which contains no reliative paths but cannot open libMesaGLU6_2.dylib since it contains libMesaGL6_2.dylib as a relative path:

```
> otool -L /Applications/exelis/idl85/bin/bin.darwin.x86_64/libMesaGL6_2.dylib 
/Applications/exelis/idl85/bin/bin.darwin.x86_64/libMesaGL6_2.dylib:
        libMesaGL6_2.dylib (compatibility version 0.0.0, current version 0.0.0)
        /opt/X11/lib/libX11.6.dylib (compatibility version 10.0.0, current version 10.0.0)
        /opt/X11/lib/libXext.6.dylib (compatibility version 11.0.0, current version 11.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)
> otool -L /Applications/exelis/idl85/bin/bin.darwin.x86_64/libMesaGLU6_2.dylib
/Applications/exelis/idl85/bin/bin.darwin.x86_64/libMesaGLU6_2.dylib:
        libMesaGLU6_2.dylib (compatibility version 0.0.0, current version 0.0.0)
        libMesaGL6_2.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)
```

Seems like there should be a way to make this work...

**Comment by BobPortmann** [comment]
OK. I have a fix for the library loading issues on mac. See https://github.com/JuliaLang/julia/issues/7004. I'll push the fix after merging this. Thanks again.

**Pull request merged**
